name: dand
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cycler=0.10.0=py36h009560c_0
  - freetype=2.8=h51f8f2c_1
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2018.0.0=8
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.0.1=py36h12c3424_0
  - libpng=1.6.34=h79bbb47_0
  - matplotlib=2.2.2=py36h153e9ff_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h452e1ab_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - numpy=1.14.2=py36h5c71026_1
  - openssl=1.0.2o=h8ea7d77_0
  - pandas=0.22.0=py36h6538335_0
  - patsy=0.5.0=py36_0
  - pip=10.0.1=py36_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyqt=5.9.2=py36h1aa27d4_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - qt=5.9.5=vc14he4a7d60_0
  - scipy=1.0.1=py36hce232c7_0
  - seaborn=0.8.1=py36h9b69545_0
  - setuptools=39.1.0=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - sqlite=3.23.1=h35aae40_0
  - statsmodels=0.8.0=py36h6189b4c_0
  - tornado=5.0.2=py36_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wheel=0.31.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - zlib=1.2.11=h8395fce_2
prefix: C:\Users\rebecca-barnes\AppData\Local\Continuum\anaconda3\envs\dand

